name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
  
    steps:
    - name: Clear Docker images
      run: sudo docker rm *
      
    - name: Pull Docker image
      run: sudo docker pull elderz6/petsalvo-frontend:latest
  
    - name: Run Docker Container
      run: sudo docker run -it -d -p 0.0.0.0:8080:8080 --name petsalvo-frontend-container elderz6/petsalvo-frontend
  

